# Generated by Django 5.2.7 on 2025-10-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tup_id',
            field=models.IntegerField(unique=True),
        ),
    ]
