# Generated by Django 5.2.7 on 2025-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_student_tup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tup_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
